### ISSUE TITLE
Not working for adding Cert

### ISSUE THREAD

**Issue by best-lucky1030** [ploi-deploy/ploi-php-sdk#47]
I tried to add cert using ploi api.

 ```
$ploi->servers($serverId)->sites($siteId)->certificates()->create(
      $certificate = $siteDomain,
      $type = 'letsencrypt',
  );
```

api call is like above.
But seeing the log, I got the message.
`Request SSL certificate failed`
`Revoke LetsEncrypt SSL certificate`

So I tried to do this as manual, but it was same.
I am not sure what's the reason and there is no solution in ploi doc?

**Comment by Cannonb4ll** [comment]
Hi,

This is not an issue for the SDK, the SDK is doing its job.

The issue here is probably something else with your domain. Please check your logs in the ploi logs tab on server level. You will see the request content there.

Also check this article: https://ploi.io/documentation/ssl/how-do-i-request-a-letsencrypt-certificate
